### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by hedgehog-genki** [hedgehog-genki/protospace-35942#1]
# URL
https://protospace-35942.herokuapp.com

**Comment by takumi0530** [comment]
@hedgehog-genki さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

### **[修正依頼箇所]**

- [x] **空の入力欄がある場合は、編集できずにそのページに留まること**
- [x] **バリデーションによって投稿ができず、そのページに留まった場合でも、入力済みの項目（画像以外）は消えないこと**
空の入力欄があるまま保存を押すと、入力済みの項目が消えてしまいます。その後、保存をもう一度押すとエラーページに遷移してしまいます。
<img width="590" alt="スクリーンショット 2021-06-08 12 50 34" src="https://user-images.githubusercontent.com/76197191/121120367-5d203080-c858-11eb-9c33-5f1165cc1051.png">

- [ ] **ログイン状態のユーザーであっても、他のユーザーのプロトタイプ編集ページのURLを直接入力して遷移しようとすると、トップページにリダイレクトされること**
他のユーザーの編集ページに遷移できてしまいます。


修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by snkw-works** [comment]
@hedgehog-genki さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、前回お伝えした点について修正が確認できませんでした。
**マージやデプロイ忘れの可能性もございます。** 今一度ご確認をお願いします！

[修正依頼箇所]
- [ ] **空の入力欄がある場合は、編集できずにそのページに留まるよう修正しましょう**
- [ ] **バリデーションによって投稿ができず、そのページに留まった場合でも、入力済みの項目（画像以外）は消えないこと**
空の入力欄があるまま保存を押すと、入力済みの項目が消えてしまいます。その後、保存をもう一度押すとエラーページに遷移してしまいます。

- [ ] **ログイン状態のユーザーであっても、他のユーザーのプロトタイプ編集ページのURLを直接入力して遷移しようとすると、トップページにリダイレクトされること**
他のユーザーの編集ページに遷移できてしまいます。

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by hedgehog-genki** [comment]
> @hedgehog-genki さん、ご提出ありがとうございます‼︎
> 動作の確認をしたところ、前回お伝えした点について修正が確認できませんでした。
> **マージやデプロイ忘れの可能性もございます。** 今一度ご確認をお願いします！
> 
> [修正依頼箇所]
> 
> * [ ]  **空の入力欄がある場合は、編集できずにそのページに留まるよう修正しましょう**
> * [ ]  **バリデーションによって投稿ができず、そのページに留まった場合でも、入力済みの項目（画像以外）は消えないこと**
>   空の入力欄があるまま保存を押すと、入力済みの項目が消えてしまいます。その後、保存をもう一度押すとエラーページに遷移してしまいます。
> * [ ]  **ログイン状態のユーザーであっても、他のユーザーのプロトタイプ編集ページのURLを直接入力して遷移しようとすると、トップページにリダイレクトされること**
>   他のユーザーの編集ページに遷移できてしまいます。
> 
> 修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
> ※新しいissueを作っていただく必要はございません。
> https://forms.gle/ZdLeprTTWhMA8aZA7

確認したところ、こちらではご指摘事項に関して正常に動作している状況です。
念の為、GIFを添付いたします。

一部、空で入力した場合、かつ保存ボタンを連打した場合
[![Image from Gyazo](https://i.gyazo.com/e36f093a0f201f78c639ce96d282b519.gif)](https://gyazo.com/e36f093a0f201f78c639ce96d282b519)

他ユーザーのeditに直接アクセスした場合
[![Image from Gyazo](https://i.gyazo.com/c343dac44c00357ff3859635cc5da7a3.gif)](https://gyazo.com/c343dac44c00357ff3859635cc5da7a3)

**Comment by takumi0530** [comment]
@hedgehog-genki さん、再度ご提出ありがとうございます‼︎
動作の確認をしたところ、
`・ログイン状態のユーザーであっても、他のユーザーのプロトタイプ編集ページのURLを直接入力して遷移しようとすると、トップページにリダイレクトされること`
こちらの修正は確認できました！

しかし、改めて修正していただきたい箇所がございましたので以下のご確認をお願いします！

### **[修正依頼箇所]**

- [ ] **空の入力欄がある場合は、編集できずにそのページに留まるよう修正しましょう**
- [ ] **バリデーションによって投稿ができず、そのページに留まった場合でも、入力済みの項目（画像以外）は消えないこと**
空の入力欄があるまま保存を押すと、入力済みの項目が消えてしまいます。その後、保存をもう一度押すとエラーページに遷移してしまいます。

https://user-images.githubusercontent.com/76197191/121135598-a16afb00-c86f-11eb-8777-dce8be2fd07c.mov




修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by hedgehog-genki** [comment]
> @hedgehog-genki さん、再度ご提出ありがとうございます‼︎
> 動作の確認をしたところ、
> `・ログイン状態のユーザーであっても、他のユーザーのプロトタイプ編集ページのURLを直接入力して遷移しようとすると、トップページにリダイレクトされること`
> こちらの修正は確認できました！
> 
> しかし、改めて修正していただきたい箇所がございましたので以下のご確認をお願いします！
> 
> ### **[修正依頼箇所]**
> * [ ]  **空の入力欄がある場合は、編集できずにそのページに留まるよう修正しましょう**
> * [ ]  **バリデーションによって投稿ができず、そのページに留まった場合でも、入力済みの項目（画像以外）は消えないこと**
>   空の入力欄があるまま保存を押すと、入力済みの項目が消えてしまいます。その後、保存をもう一度押すとエラーページに遷移してしまいます。
> 
>  default.mov 
> 修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
> ※新しいissueを作っていただく必要はございません。
> https://forms.gle/ZdLeprTTWhMA8aZA7

失礼しました、編集ページでのお話ですね。
申し訳ございません。
修正致しましたので、ご確認お願いいたします。

**Comment by takumi0530** [comment]
@hedgehog-genki さん、再度ご提出ありがとうございます‼︎
上記、問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください🍀
